server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:6541/ewm-stats
spring.datasource.username=ewm
spring.datasource.password=ewm
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
