name: CI

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Start Docker Compose
        run: docker compose up -d
        
      - name: Wait for services
        run: |
          echo "Waiting for stats-server..."
          ./tests/.github/workflows/wait-for-it.sh -t 120 localhost:9090
          echo "Waiting for ewm-service..."
          ./tests/.github/workflows/wait-for-it.sh -t 180 localhost:8080
          
      - name: Check container logs if failed
        if: failure()
        run: |
          docker compose ps
          docker compose logs
          
      - name: Run API tests
        run: |
          # Ваши тесты здесь
          mvn test
          
      - name: Stop Docker Compose
        if: always()
        run: docker compose down
